package database

import "vector-search-project/internal/model"

func GetFruitsToSeed() []*model.Fruit {
	return []*model.Fruit{
		{Name: "Banana", Origin: "South America", BestFor: "Snacks and smoothies", Texture: "Creamy", Flavor: "Sweet", Season: "All Season", Color: "Yellow", Price: 0.50},
		{Name: "Lemon", Origin: "Europe", BestFor: "Juicing and seasoning", Texture: "Juicy", Flavor: "Extra Sour", Season: "Spring, Winter", Color: "Yellow", Price: 0.30},
		{Name: "Red Apple", Origin: "North America", BestFor: "Eating fresh", Texture: "Crunchy", Flavor: "Sweet", Season: "Fall", Color: "Red", Price: 1.00},
		{Name: "Green Apple", Origin: "Oceania", BestFor: "Baking and salads", Texture: "Crisp", Flavor: "Tart and Sour", Season: "Fall", Color: "Green", Price: 1.10},
		{Name: "Strawberry", Origin: "Europe", BestFor: "Desserts", Texture: "Soft", Flavor: "Sweet and tangy", Season: "Spring, Summer", Color: "Red", Price: 2.50},
		{Name: "Mango", Origin: "South Asia", BestFor: "Smoothies and salsas", Texture: "Fibrous", Flavor: "Sweet and tropical", Season: "Spring, Summer", Color: "Yellow", Price: 1.50},
		{Name: "Pineapple", Origin: "South America", BestFor: "Grilling and juices", Texture: "Tough", Flavor: "Sweet and acidic", Season: "All Season", Color: "Yellow/Brown", Price: 3.00},
		{Name: "Blueberry", Origin: "North America", BestFor: "Pancakes and muffins", Texture: "Firm", Flavor: "Sweet and earthy", Season: "Summer", Color: "Blue", Price: 4.00},
		{Name: "Watermelon", Origin: "South America", BestFor: "Hydration and fruit salads", Texture: "Grainy", Flavor: "Sweet and refreshing", Season: "Summer", Color: "Green/Red", Price: 5.00},
		{Name: "Peach", Origin: "East Asia", BestFor: "Pies and cobblers", Texture: "Soft", Flavor: "Sweet and floral", Season: "Summer", Color: "Orange/Pink", Price: 1.20},
		{Name: "Plum", Origin: "Europe", BestFor: "Jams and tarts", Texture: "Smooth", Flavor: "Sweet and tart", Season: "Summer, Fall", Color: "Purple", Price: 0.80},
		{Name: "Cherry", Origin: "West Asia", BestFor: "Snacking and garnish", Texture: "Meaty", Flavor: "Sweet or sour", Season: "Summer", Color: "Red", Price: 5.50},
		{Name: "Pear", Origin: "South America", BestFor: "Poaching and cheese pairings", Texture: "Gritty", Flavor: "Sweet and mild", Season: "Fall, Winter", Color: "Green/Yellow/Brown", Price: 0.90},
		{Name: "Orange", Origin: "South America", BestFor: "Juice and vit-C", Texture: "Pulpy", Flavor: "Sweet and citrusy", Season: "Winter", Color: "Orange", Price: 0.60},
		{Name: "Grape", Origin: "Europe", BestFor: "Wine and table snacking", Texture: "Juicy", Flavor: "Sweet and musky", Season: "Fall", Color: "Purple/Green/Red", Price: 2.00},
		{Name: "Kiwi", Origin: "Oceania", BestFor: "Garnish and fruit cups", Texture: "Fleshy", Flavor: "Sweet and tart", Season: "Winter, Spring", Color: "Brown/Green", Price: 0.70},
		{Name: "Pomegranate", Origin: "Middle East", BestFor: "Salad toppings and juice", Texture: "Crunchy seeds", Flavor: "Sweet and astringent", Season: "Fall, Winter", Color: "Red", Price: 2.50},
		{Name: "Avocado", Origin: "North America", BestFor: "Guacamole and toast", Texture: "Buttery", Flavor: "Nutty and savory", Season: "All Season", Color: "Green/Black", Price: 1.80},
		{Name: "Dragon Fruit", Origin: "South East Asia", BestFor: "Smoothie bowls", Texture: "Crunchy seeds", Flavor: "Mild and sweet", Season: "Summer, Fall", Color: "Pink/White", Price: 4.50},
		{Name: "Papaya", Origin: "North America", BestFor: "Digestive aid and smoothies", Texture: "Soft", Flavor: "Sweet and musky", Season: "All Season", Color: "Orange/Yellow/Green", Price: 2.20},
		{Name: "Guava", Origin: "South East Asia", BestFor: "Jellies and juices", Texture: "Crunchy seeds", Flavor: "Sweet and fragrant", Season: "Winter, Spring", Color: "Green/Pink", Price: 1.40},
		{Name: "Fig", Origin: "West Asia", BestFor: "Baking and appetizers", Texture: "Chewy", Flavor: "Sweet and honey-like", Season: "Summer, Fall", Color: "Purple/Green", Price: 3.50},
		{Name: "Apricot", Origin: "West Asia", BestFor: "Dried snacks and preserves", Texture: "Velvety", Flavor: "Sweet and tart", Season: "Summer", Color: "Orange", Price: 1.10},
		{Name: "Blackberry", Origin: "North America", BestFor: "Baking and jams", Texture: "Bumpy", Flavor: "Tart and sweet", Season: "Summer", Color: "Black/Deep Purple", Price: 3.80},
		{Name: "Raspberry", Origin: "North America", BestFor: "Toppings and desserts", Texture: "Hollow", Flavor: "Tart and delicate", Season: "Summer", Color: "Red", Price: 4.20},
		{Name: "Blueberry", Origin: "North America", BestFor: "Pies and pancakes", Texture: "Firm", Flavor: "Sweet and tangy", Season: "Summer", Color: "Blue", Price: 3.50},
		{Name: "Cranberry", Origin: "North America", BestFor: "Sauces and juices", Texture: "Firm", Flavor: "Tart", Season: "Fall", Color: "Red", Price: 2.80},
		{Name: "Gooseberry", Origin: "Europe", BestFor: "Tarts and jams", Texture: "Translucent", Flavor: "Tart and sweet", Season: "Summer", Color: "Green/Yellow/Red", Price: 3.10},
		{Name: "Mulberry", Origin: "East Asia", BestFor: "Desserts", Texture: "Soft", Flavor: "Sweet", Season: "Spring, Summer", Color: "Black/Red/White", Price: 4.50},
		{Name: "Elderberry", Origin: "Europe", BestFor: "Syrups and wines", Texture: "Juicy", Flavor: "Tart", Season: "Summer, Fall", Color: "Black", Price: 5.00},
		{Name: "Lychee", Origin: "East Asia", BestFor: "Fresh fruit salads", Texture: "Jelly-like", Flavor: "Sweet and floral", Season: "Summer", Color: "Pink/White", Price: 6.00},
		{Name: "Rambutan", Origin: "South East Asia", BestFor: "Snacking", Texture: "Fleshy", Flavor: "Sweet and creamy", Season: "Summer, Winter", Color: "Red/White", Price: 5.50},
		{Name: "Mangosteen", Origin: "South East Asia", BestFor: "Desserts", Texture: "Soft", Flavor: "Sweet and tangy", Season: "Summer", Color: "Purple/White", Price: 8.00},
		{Name: "Durian", Origin: "South East Asia", BestFor: "Baking", Texture: "Custard-like", Flavor: "Sweet and pungent", Season: "Summer", Color: "Green/Yellow", Price: 15.00},
		{Name: "Star Fruit", Origin: "South East Asia", BestFor: "Garnish", Texture: "Crisp", Flavor: "Sweet and tart", Season: "Fall, Winter", Color: "Yellow/Green", Price: 3.20},
		{Name: "Passion Fruit", Origin: "South America", BestFor: "Juices and desserts", Texture: "Pulpy", Flavor: "Tart and fragrant", Season: "Summer, Winter", Color: "Purple/Yellow", Price: 4.00},
		{Name: "Persimmon", Origin: "East Asia", BestFor: "Baking and snacks", Texture: "Soft", Flavor: "Sweet and honey-like", Season: "Fall, Winter", Color: "Orange", Price: 2.50},
		{Name: "Quince", Origin: "West Asia", BestFor: "Jams and stews", Texture: "Tough", Flavor: "Tart and fragrant", Season: "Fall", Color: "Yellow", Price: 3.00},
		{Name: "Cantaloupe", Origin: "North America", BestFor: "Fruit salads", Texture: "Juicy", Flavor: "Sweet", Season: "Summer", Color: "Tan/Orange", Price: 2.50},
		{Name: "Honeydew", Origin: "North America", BestFor: "Refreshments", Texture: "Juicy", Flavor: "Sweet", Season: "Summer", Color: "Green", Price: 3.00},
		{Name: "Blood Orange", Origin: "Europe", BestFor: "Salads and juice", Texture: "Pulpy", Flavor: "Sweet and tart", Season: "Winter, Spring", Color: "Orange/Deep Red", Price: 1.50},
		{Name: "Clementine", Origin: "Europe", BestFor: "Snacking", Texture: "Juicy", Flavor: "Sweet", Season: "Winter", Color: "Orange", Price: 0.80},
		{Name: "Tangerine", Origin: "North America", BestFor: "Snacking", Texture: "Juicy", Flavor: "Sweet", Season: "Winter, Spring", Color: "Orange", Price: 1.00},
		{Name: "Pomelo", Origin: "East Asia", BestFor: "Fresh snacks", Texture: "Coarse", Flavor: "Sweet and bitter", Season: "Winter", Color: "Green/Yellow", Price: 4.00},
		{Name: "Dates", Origin: "Middle East", BestFor: "Baking and snacks", Texture: "Chewy", Flavor: "Very sweet", Season: "All Season", Color: "Brown", Price: 5.00},
	}
}
